version: "3.9"

networks:
  internal:

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "coupon-shop"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - internal
  coupon-shop-admin:
    ports:
      - '8080:8080'
    build: .
    env_file:
      - ./config/.env
    networks:
      - internal
    depends_on:
      - postgres