version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "coupon-shop"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:latest
    command: redis-server --requirepass 123
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "ping"]
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    healthcheck:
      test: curl -s http://elasticsearch01:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - .:/data/elastic

  coupon-shop-admin:
    container_name: coupon-shop-admin
    image: ripperacskt/coupon-shop-admin:latest
    volumes:
      - ./internal/repository/migrations:/app/internal/repository/migrations
      - ./store:/app/store
    env_file:
      - ./config/.env
    depends_on:
      - postgres
      - redis
    ports:
      - "4000:4000"
      - "8081:8081"

  coupon-shop:
    container_name: coupon-shop
    image: ripperacskt/coupon-shop:latest
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
  coupon-shop-front:
    container_name: coupon-shop-front
    image: ripperacskt/coupon-shop-front:latest
    ports:
      - "4001:9999"
