version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "coupon-shop"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    command: >
      --requirepass 123
    volumes:
      - .:/data/redis
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    ports:
      - "6379:6379"

  coupon-shop-admin:
    ports:
      - '8080:8080'
    build: .
    env_file:
      - ./config/.env
    depends_on:
      - postgres
      - redis